BLOX_SEG__UPPER_LEFT=(time host cwd)
BLOX_SEG__UPPER_RIGHT=(pyenv virtualenv)
BLOX_SEG__LOWER_LEFT=(git symbol)

BLOX_CONF__BLOCK_SEPARATOR=""
BLOX_CONF__SYMBOL_SEPARATOR=" "
BLOX_BLOCK__SYMBOL_SYMBOL=('==>')
BLOX_BLOCK__SYMBOL_EXIT_SYMBOL=('E=>')

BLOX_BLOCK__CWD_TRUNC=2
BLOX_BLOCK__GIT_COMMIT_SHOW=false
BLOX_BLOCK__HOST_MACHINE_SHOW_ALWAYS=true
BLOX_BLOCK__HOST_USER_SHOW_ALWAYS=false

# Prompt Colors
CP_ORANGE='#ff6c2c'
SAINTS_GOLD='#D2B877'

BLOX_BLOCK__SYMBOL_COLOR="${CP_ORANGE}"
BLOX_BLOCK__CWD_COLOR="${SAINTS_GOLD}"
BLOX_BLOCK__HOST_USER_COLOR="${CP_ORANGE}"
BLOX_BLOCK__HOST_MACHINE_COLOR="${CP_ORANGE}"
BLOX_BLOCK__TIME_COLOR="${CP_ORANGE}"
BLOX_CONF__SURROUND_COLOR="white"
