# Created by newuser for 5.3.1
# If you come from bash you might have to change your $PATH.
fpath+=~/.zsh_custom/zfunc
export PATH=/usr/local/opt/gnubin:${HOME}/.python/bin:/usr/local/sbin:$HOME/.bin:${HOME}/.local/bin:/usr/local/opt/curl/bin:/usr/local/bin:$PATH

export ANTIBODY_HOME=${HOME}/.zsh_custom/plugins

source <(antibody init)
antibody bundle < ~/.zsh_custom/zsh_plugins.txt

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="aussiegeek"
#ZSH_THEME='alien'

BLOX_SEG__UPPER_LEFT=(time host cwd)
BLOX_SEG__UPPER_RIGHT=(pyenv virtualenv)
BLOX_SEG__LOWER_LEFT=(git symbol)
BLOX_CONF__BLOCK_SEPARATOR=""
BLOX_CONF__SYMBOL_SEPARATOR=" "

BLOX_BLOCK__SYMBOL_SYMBOL=('==>')
BLOX_BLOCK__SYMBOL_EXIT_SYMBOL=('!=>')

BLOX_BLOCK__CWD_TRUNC=2
BLOX_BLOCK__GIT_COMMIT_SHOW=false
BLOX_BLOCK__HOST_MACHINE_SHOW_ALWAYS=true
BLOX_BLOCK__HOST_USER_SHOW_ALWAYS=false

# Prompt Colors
CP_ORANGE='#ff6c2c'
SAINTS_GOLD='#D2B877'

BLOX_BLOCK__SYMBOL_COLOR="${CP_ORANGE}"
BLOX_BLOCK__CWD_COLOR="${SAINTS_GOLD}"
BLOX_BLOCK__HOST_USER_COLOR="${CP_ORANGE}"
BLOX_BLOCK__HOST_MACHINE_COLOR="${CP_ORANGE}"
BLOX_BLOCK__TIME_COLOR="${CP_ORANGE}"
BLOX_CONF__SURROUND_COLOR="white"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.zsh_custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(python)

source $ZSH/oh-my-zsh.sh

# User configuration

source ~/.config/r.grassmuck-openrc.sh

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.7

source ${ZSH_CUSTOM}/*.zsh
export PATH="/Users/rickygrassmuck/Library/Python/3.7/bin":"/usr/local/opt/openssl/bin:$HOME/.poetry/bin:$PATH"
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
export OP_SESSION_cpanel="yYLfL9Eqzai8M9Nu4b9LuZtvvZupsxZbFqAlPJ6EcKc"
