# Created by newuser for 5.3.1
# If you come from bash you might have to change your $PATH.
export ZSH_CUSTOM=~/.zsh_custom
export ZSH=${HOME}/.oh-my-zsh
source ${ZSH}/oh-my-zsh.sh

fpath+=${ZSH_CUSTOM}/zfunc
source ${ZSH_CUSTOM}/*.zsh
source <(antibody init) && antibody bundle < ~/.zsh_custom/zsh_plugins.txt

# Uncomment the following line to use case-sensitive completion.
plugins=(python osx)
CASE_SENSITIVE="true"
DISABLE_UPDATE_PROMPT=true
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='nvim'
fi

test_source "~/.iterm2_shell_integration.zsh"
test_source " ~/.fzf.zsh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /Users/rickygrassmuck/Development/bin/nomad nomad

